# Generated by Django 3.1.2 on 2021-01-29 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vender', '0001_initial'),
        ('Admin1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('adress', models.TextField()),
                ('items', models.ManyToManyField(to='vender.FoodItemsModel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRegistrationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField(unique=True)),
                ('adress', models.TextField()),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin1.citymodel')),
            ],
        ),
    ]
